# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guide.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bguide.proto\" \n\x0bTaskRequest\x12\x11\n\ttask_name\x18\x01 \x01(\t\"3\n\tTaskReply\x12\x11\n\ttask_name\x18\x01 \x01(\t\x12\x13\n\x0btask_number\x18\x02 \x01(\t2\x8c\x01\n\x08TaskMenu\x12$\n\x06\x44oTask\x12\x0c.TaskRequest\x1a\n.TaskReply\"\x00\x12*\n\nDeleteTask\x12\x0c.TaskRequest\x1a\n.TaskReply\"\x00\x30\x01\x12.\n\x0cOvewriteTask\x12\x0c.TaskRequest\x1a\n.TaskReply\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guide_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKREQUEST._serialized_start=15
  _TASKREQUEST._serialized_end=47
  _TASKREPLY._serialized_start=49
  _TASKREPLY._serialized_end=100
  _TASKMENU._serialized_start=103
  _TASKMENU._serialized_end=243
# @@protoc_insertion_point(module_scope)
