# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import guide_pb2 as guide__pb2


class TaskMenuStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoTask = channel.unary_unary(
                '/TaskMenu/DoTask',
                request_serializer=guide__pb2.TaskRequest.SerializeToString,
                response_deserializer=guide__pb2.TaskReply.FromString,
                )
        self.DeleteTask = channel.unary_stream(
                '/TaskMenu/DeleteTask',
                request_serializer=guide__pb2.TaskRequest.SerializeToString,
                response_deserializer=guide__pb2.TaskReply.FromString,
                )
        self.OvewriteTask = channel.stream_stream(
                '/TaskMenu/OvewriteTask',
                request_serializer=guide__pb2.TaskRequest.SerializeToString,
                response_deserializer=guide__pb2.TaskReply.FromString,
                )


class TaskMenuServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OvewriteTask(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskMenuServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DoTask,
                    request_deserializer=guide__pb2.TaskRequest.FromString,
                    response_serializer=guide__pb2.TaskReply.SerializeToString,
            ),
            'DeleteTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=guide__pb2.TaskRequest.FromString,
                    response_serializer=guide__pb2.TaskReply.SerializeToString,
            ),
            'OvewriteTask': grpc.stream_stream_rpc_method_handler(
                    servicer.OvewriteTask,
                    request_deserializer=guide__pb2.TaskRequest.FromString,
                    response_serializer=guide__pb2.TaskReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TaskMenu', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskMenu(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskMenu/DoTask',
            guide__pb2.TaskRequest.SerializeToString,
            guide__pb2.TaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/TaskMenu/DeleteTask',
            guide__pb2.TaskRequest.SerializeToString,
            guide__pb2.TaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OvewriteTask(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/TaskMenu/OvewriteTask',
            guide__pb2.TaskRequest.SerializeToString,
            guide__pb2.TaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
